categories:
  cs:
    - cs.AI
    - cs.AR
    - cs.CC
    - cs.CE
    - cs.CG
    - cs.CL
    - cs.CR
    - cs.CV
    - cs.DB
    - cs.DC
    - cs.DM
    - cs.DS
    - cs.ET
    - cs.FL
    - cs.GL
    - cs.GR
    - cs.GT
    - cs.HC
    - cs.IR
    - cs.IT
    - cs.LG
    - cs.LO
    - cs.MA
    - cs.MM
    - cs.MS
    - cs.NI
    - cs.NE
    - cs.NA
    - cs.OS
    - cs.PF
    - cs.PL
    - cs.RO
    - cs.SE
    - cs.SD
    - cs.SC
    - cs.SI
    - cs.SY
  econ:
    - econ.EM
    - econ.GN
    - econ.TH
  eess:
    - eess.AS
    - eess.IV
    - eess.SP
  math:
    - math.AC
    - math.AG
    - math.AT
    - math.AP
    - math.CT
    - math.CA
    - math.CO
    - math.CV
    - math.DG
    - math.DS
    - math.FA
    - math.GM
    - math.GN
    - math.GT
    - math.GR
    - math.IT
    - math.KT
    - math.LO
    - math.MP
    - math.MG
    - math.NT
    - math.NA
    - math.OA
    - math.OC
    - math.PR
    - math.QA
    - math.RT
    - math.RA
    - math.SP
    - math.ST
    - math.SG
  phys:
    - astro-ph.CO
    - astro-ph.EP
    - astro-ph.GA
    - astro-ph.HE
    - astro-ph.IM
    - astro-ph.SR
    - cond-mat.dis-nn
    - cond-mat.mes-hall
    - cond-mat.mtrl-sci
    - cond-mat.other
    - cond-mat.quant-gas
    - cond-mat.soft
    - cond-mat.stat-mech
    - cond-mat.str-el
    - cond-mat.supr-con
    - gr-qc
    - hep-ex
    - hep-lat
    - hep-ph
    - hep-th
    - math-ph
    - nlin.AO
    - nlin.CD
    - nlin.CG
    - nlin.PS
    - nlin.SI
    - nucl-ex
    - nucl-th
    - physics.acc-ph
    - physics.app-ph
    - physics.ao-ph
    - physics.atom-ph
    - physics.atm-clus
    - physics.bio-ph
    - physics.chem-ph
    - physics.class-ph
    - physics.comp-ph
    - physics.data-an
    - physics.ed-ph
    - physics.flu-dyn
    - physics.gen-ph
    - physics.geo-ph
    - physics.hist-ph
    - physics.ins-det
    - physics.med-ph
    - physics.optics
    - physics.plasm-ph
    - physics.pop-ph
    - physics.soc-ph
    - physics.space-ph
    - quant-ph
  q-bio:
    - q-bio.BM
    - q-bio.GN
    - q-bio.MN
    - q-bio.NC
    - q-bio.OT
    - q-bio.PE
    - q-bio.QM
    - q-bio.SC
    - q-bio.TO
  q-fin:
    - q-fin.CP
    - q-fin.EC
    - q-fin.MF
    - q-fin.PR
    - q-fin.RM
    - q-fin.TR
  stat:
    - stat.AP
    - stat.CO
    - stat.ME
    - stat.ML
    - stat.OT
    - stat.TH